apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JarenDamm/test-job.git
    path: jobs
    targetRevision: HEAD   
  destination:
    server: "https://kubernetes.default.svc"    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true